InfluxDb output : allow reusing writer
jmxtrans/jmxtrans pull request #794
Opened 2021-03-19 10:12 UTC by hightea

Add equals and hashcode on InfluxDbWriterFactory to allow sharing the writer between servers and queries

2021-03-23 07:42 UTC, gquintana requested changes
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.2.2:mutationCoverage (pitest) on project jmxtrans-output-influxdb: Mutation score of 26 is below threshold of 45 -> [Help 1]

2021-03-23 10:25 UTC, hightea commented on jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterFactory.java
> +@EqualsAndHashCode(exclude = {"influxDB"})
In the ServerListBuilder, the reuse of existing outputWriterFactory is made with the SingletonOutputWriterFactory.
The unicity ("singleton") of the SingletonOutputWriterFactory is based on the equals / hashcode of thisi class which is delegated to the equals / hashcode  of the outputWriterFactory. So defining these methods on the OutputWriterFactory allow the reuse of the factory between several queries / servers.

2021-03-23 10:26 UTC, hightea commented
I'm working on the org.pitest:pitest-maven:1.2.2:mutationCoverage (pitest)  failure : 
This simply need me to add some tests to the InfluxDbWriterFactory... work in progress

2021-03-30 18:36 UTC, hightea commented on jmxtrans-output/jmxtrans-output-influxdb/src/main/java/com/googlecode/jmxtrans/model/output/InfluxDbWriterFactory.java
> +	@Getter(AccessLevel.PACKAGE)
Only to have some access to data to do some tests...

2021-03-30 18:46 UTC, merged